version: "3.7"
services:
  postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/:/var/lib/postgresql/

networks:
   default:
     driver: bridge